In [45]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [46]:
import os
os.chdir("C:\\Users\\jaiveer.karra.1\\Google Drive\\02 Lab Data\\Python")


In [47]:
import pandas as pd
df=pd.read_csv("fake_or_real_news.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
Unnamed: 0    6335 non-null int64
title         6335 non-null object
text          6335 non-null object
label         6335 non-null object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [48]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [49]:
X=df["text"]
type(X)

pandas.core.series.Series

In [50]:
y=df.label
type(y)
y.head()

0    FAKE
1    FAKE
2    REAL
3    FAKE
4    REAL
Name: label, dtype: object

In [51]:
train_test_split?

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
                                    X, y, test_size=0.3, random_state=42)

In [53]:
X_train.shape

(4434,)

In [54]:
X_test.shape

(1901,)

In [55]:
y_train.shape

(4434,)

In [56]:
(X_train.ndim,y_train.ndim)

(1, 1)

In [57]:
count_vetorizer=CountVectorizer(stop_words="english")

In [58]:
count_vetorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [59]:
count_train=count_vetorizer.fit_transform(X_train)
count_train

<4434x57841 sparse matrix of type '<class 'numpy.int64'>'
	with 1151644 stored elements in Compressed Sparse Row format>

In [60]:
X_train.shape

(4434,)

In [61]:
X_train[1]

'Google Pinterest Digg Linkedin Reddit Stumbleupon Print Delicious Pocket Tumblr \nThere are two fundamental truths in this world: Paul Ryan desperately wants to be president. And Paul Ryan will never be president. Today proved it. \nIn a particularly staggering example of political cowardice, Paul Ryan re-re-re-reversed course and announced that he was back on the Trump Train after all. This was an aboutface from where he was a few weeks ago. He had previously declared he would not be supporting or defending Trump after a tape was made public in which Trump bragged about assaulting women. Suddenly, Ryan was appearing at a pro-Trump rally and boldly declaring that he already sent in his vote to make him President of the United States. It was a surreal moment. The figurehead of the Republican Party dosed himself in gasoline, got up on a stage on a chilly afternoon in Wisconsin, and lit a match. . @SpeakerRyan says he voted for @realDonaldTrump : “Republicans, it is time to come home” ht

In [62]:
y_train[1]

'FAKE'

In [63]:
X_test[233]

'On this day in 1973, J. Fred Buzhardt, a lawyer defending President Richard Nixon in the Watergate case, revealed that a key White House tape had an 18...'

In [64]:
X_train[234]

'By wmw_admin on September 16, 2008 \nThe ‘dots’ you are not supposed to connect… Affidavit of Richard Tomlinson By wmw_admin on February 14, 2008 \n“I firmly believe that there exist documents held by the British Secret Intelligence Service (MI6) that would yield important new evidence into the cause and circumstances leading to the death of the Princess of Wales.” They Live By wmw_admin on August 19, 2012 \nConsidered by some as prophetic, many will find eerie echoes of present day concerns in John Carpenters 24-year-old ‘They Live’. View the cult classic here The Anglo-Saxon Mission Part I By wmw_admin on March 1, 2010 \nBill Ryan talks to a former City of London insider who participated in a meeting where the elite’s plans for depopulation were discussed. The meeting, which took place in 2005, also discussed a planned financial collapse Who Really Murdered Holly Wells and Jessica Chapman? By wmw_admin on February 28, 2015 \nRevelations that a US soldier was the killer would have je

In [65]:
count_vetorizer.get_feature_names().index("questions")
                                          

41286

In [66]:
len(count_vetorizer.get_stop_words())

318

In [67]:
count_train.shape

(4434, 57841)

In [68]:
count_train.toarray([1,4433])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [69]:
count_test=count_vetorizer.transform(X_test)
count_test

<1901x57841 sparse matrix of type '<class 'numpy.int64'>'
	with 502974 stored elements in Compressed Sparse Row format>

In [70]:
print(count_vetorizer.get_feature_names()[11:20])

['002', '003', '004', '004s', '006', '00684', '006s', '007', '007s']


tfidvectorizer

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [72]:
tfid_vectorizer=TfidfVectorizer()
tfid_vectorizer


TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [73]:
tfid_train=tfid_vectorizer.fit_transform(X_train)
tfid_train

<4434x58149 sparse matrix of type '<class 'numpy.float64'>'
	with 1494485 stored elements in Compressed Sparse Row format>

In [76]:
tfid_test=tfid_vectorizer.transform(X_test)
tfid_test

<1901x58149 sparse matrix of type '<class 'numpy.float64'>'
	with 653153 stored elements in Compressed Sparse Row format>

In [78]:
tfid_train[0:2].toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [80]:
tfid_vectorizer.get_feature_names()[0:10]

['00',
 '000',
 '0000',
 '000000031',
 '00000031',
 '0001',
 '0002',
 '000billion',
 '000ft',
 '000km']

In [82]:
count_vetorizer.get_feature_names()[0:10]==tfid_vectorizer.get_feature_names()[0:10]

True

In [87]:
count_df=pd.DataFrame(data=count_train.A,columns=count_vetorizer.get_feature_names())
type(count_df)

pandas.core.frame.DataFrame

In [88]:
count_df.head()

00  000  0000  000000031  00000031  0001  0002  000billion  000ft  000km  \
0   0    0     0          0         0     0     0           0      0      0   
1   0    0     0          0         0     0     0           0      0      0   
2   0    0     0          0         0     0     0           0      0      0   
3   0    4     0          0         0     0     0           0      0      0   
4   0    0     0          0         0     0     0           0      0      0   

   ...  שתי  תאמצנה  תוצאה  תחל  תיירות  תנותק  תעודת  תתרכז  القادمون  عربي  
0  ...    0       0      0    0       0      0      0      0         0     0  
1  ...    0       0      0    0       0      0      0      0         0     0  
2  ...    0       0      0    0       0      0      0      0         0     0  
3  ...    0       0      0    0       0      0      0      0         0     0  
4  ...    0       0      0    0       0      0      0      0         0     0  

[5 rows x 57841 columns]

In [89]:
tfid_df=pd.DataFrame(data=tfid_train.A,columns=tfid_vectorizer.get_feature_names())
tfid_df.head()

00       000  0000  000000031  00000031  0001  0002  000billion  000ft  \
0  0.0  0.000000   0.0        0.0       0.0   0.0   0.0         0.0    0.0   
1  0.0  0.000000   0.0        0.0       0.0   0.0   0.0         0.0    0.0   
2  0.0  0.000000   0.0        0.0       0.0   0.0   0.0         0.0    0.0   
3  0.0  0.033546   0.0        0.0       0.0   0.0   0.0         0.0    0.0   
4  0.0  0.000000   0.0        0.0       0.0   0.0   0.0         0.0    0.0   

   000km  ...  שתי  תאמצנה  תוצאה  תחל  תיירות  תנותק  תעודת  תתרכז  القادمون  \
0    0.0  ...  0.0     0.0    0.0  0.0     0.0    0.0    0.0    0.0       0.0   
1    0.0  ...  0.0     0.0    0.0  0.0     0.0    0.0    0.0    0.0       0.0   
2    0.0  ...  0.0     0.0    0.0  0.0     0.0    0.0    0.0    0.0       0.0   
3    0.0  ...  0.0     0.0    0.0  0.0     0.0    0.0    0.0    0.0       0.0   
4    0.0  ...  0.0     0.0    0.0  0.0     0.0    0.0    0.0    0.0       0.0   

   عربي  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  

[5 rows x 58149 columns]

In [94]:
diff=set(count_df.columns)-set(tfid_df.columns)
diff

set()

##training and testing the model by usiing Navie bayes

In [96]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [136]:
nb_classifier=MultinomialNB(alpha=0.03)
nb_classifier

MultinomialNB(alpha=0.03, class_prior=None, fit_prior=True)

In [137]:
nb_classifier.fit(count_train,y_train)

MultinomialNB(alpha=0.03, class_prior=None, fit_prior=True)

In [138]:
y_pred=nb_classifier.predict(count_test)
y_pred

array(['FAKE', 'FAKE', 'FAKE', ..., 'FAKE', 'REAL', 'REAL'], dtype='<U4')

In [139]:
acc_count=accuracy_score(y_test,y_pred)
acc_count

0.8932140978432404

In [140]:
conn_count=confusion_matrix(y_test,y_pred,labels=["FAKE","REAL"])
conn_count

array([[842, 126],
       [ 77, 856]], dtype=int64)

In [141]:
nb_classifier1=MultinomialNB(alpha=0.03)
nb_classifier1.fit(tfid_train,y_train)

MultinomialNB(alpha=0.03, class_prior=None, fit_prior=True)

In [142]:
y_tfid_pred=nb_classifier1.predict(tfid_test)
y_tfid_pred

array(['FAKE', 'FAKE', 'FAKE', ..., 'FAKE', 'REAL', 'REAL'], dtype='<U4')

In [125]:
acc_tfid=accuracy_score(y_test,y_tfid_pred)
acc_tfid

0.8921620199894792

In [126]:
conn_tfid=confusion_matrix(y_test,y_tfid_pred)
conn_tfid

array([[832, 136],
       [ 69, 864]], dtype=int64)

In [130]:
824+857

1681

In [128]:
553+924

1477

In [111]:
415+9+1477

1901

In [129]:
832+864

1696

## Logistic regression for text classification

In [143]:
from sklearn.linear_model import LogisticRegression

In [144]:
log=LogisticRegression()
log.fit(count_train,y_train)

C:\Users\jaiveer.karra.1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [145]:
pred_log=log.predict(count_test)
pred_log

array(['FAKE', 'FAKE', 'FAKE', ..., 'FAKE', 'REAL', 'REAL'], dtype=object)

In [146]:
acc_log=accuracy_score(y_test,pred_log)
acc_log

0.9126775381378222

In [153]:
cnn_log_coun=confusion_matrix(y_test,pred_log)
cnn_log_coun

array([[896,  72],
       [ 94, 839]], dtype=int64)

In [147]:
log_tfid=LogisticRegression()
log_tfid.fit(tfid_train,y_train)

C:\Users\jaiveer.karra.1\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [148]:
pred_log_tfid=log_tfid.predict(tfid_test)


In [150]:
acc_log_tfid=accuracy_score(y_test,pred_log_tfid)
acc_log_tfid

0.9147816938453446

In [154]:
cnn_log_tfid=confusion_matrix(y_test,pred_log_tfid)
cnn_log_tfid

array([[903,  65],
       [ 97, 836]], dtype=int64)